version: "3.8"
services:
  frontend:
    build: .
    container_name: pairfeedllm-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:5000
